server:
  port: 8081
eureka:
  client:
    serviceUrl:
      register-with-eureka: true
      fetch-registry: true
      defaultZone: http://admin:123456@localhost:9090/eureka
  instance:
    preferIpAddress: true

spring:
  application:
    name: config-server