server:
  port: 8081
eureka:
  client:
    serviceUrl:
      register-with-eureka: true
      fetch-registry: true
      defaultZone: http://localhost:9090/eureka
  instance:
    preferIpAddress: true